### ISSUE TITLE
I need some help setting up Yelp API

### ISSUE THREAD

**Issue by jfkn1ght** [madenwala/Yelp.API#13]
I need some assistance getting the Yelp API up and running on my project. I'm fairly new to C# programming. I have downloaded the API off nuGet through Visual Studio 2017. It is a Visual C# .Net Core console App.

My output is: 

> System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[System.Threading.Tasks.VoidTaskResult,yelp_api_demo.Program+<YelpAPICommands>d__1]

Here is my code:
    
    using System;
    using System.Threading.Tasks;
    namespace yelp_api_demo
    {
        class Program
        {
            static void Main(string[] args)
            {
                Console.WriteLine(YelpAPICommands());

                Console.ReadKey();
            }

            static async Task YelpAPICommands()
        {
            var client = new Yelp.Api.Client("API KEY HERE");
            var results = await client.SearchBusinessesAllAsync("cupcakes", 37.786882, -122.399972);
            return;
        }
    }
    } 

I'm getting no compiling errors but I do get a warning that says: 
>"Warning	NU1701	Package 'Yelp.Api 1.3.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project."

I still get similar problems with a regular C# console app.
Thank you for any assistance.

**Comment by Pinski** [comment]
This NuGet package doesn't target .NET Core so it won't work with a .NET Core project (which is what that warning means).  I've forked this project and added support for .NET Core along with some other features.  

https://github.com/Pinski/Yelp.Api.Web

Currently I've only tested it with .NET Core 1.x but it might work with .NET Core 2.x.  I'm in the process of putting in some missing APIs this month, cleaning up some code, and then I'm going to test it with more versions of .NET Core and maybe .NET Framework. 

Feel free to check it out and let me know if you have any issues.

**Comment by jfkn1ght** [comment]
> This NuGet package doesn't target .NET Core so it won't work with a .NET Core project (which is what that warning means).  I've forked this project and added support for .NET Core along with some other features.
> https://github.com/Pinski/Yelp.Api.Web
> Currently I've only tested it with .NET Core 1.x but it might work with .NET Core 2.x.  I'm in the process of putting in some missing APIs this month, cleaning up some code, and then I'm going to test it with more versions of .NET Core and maybe .NET Framework.
> Feel free to check it out and let me know if you have any issues.

Thank you for your response! 
I finally understand that it wont work on .NET core. I have worked on this more. It runs now, however the console outputs the following one line. What is my code missing?:

> Yelp.Api.Models.SearchResponse

Here is my complete code:
```
using System;
using System.Threading.Tasks;
using Yelp.Api;

namespace yelp_example_test3
{
    class Program
    {
        static void Main(string[] args)
        {        
            YelpAPICommands().Wait();
            Console.ReadKey();
        }

        static async Task YelpAPICommands()
        {
            var client = new Client("API KEY HERE");
            var results = await client.SearchBusinessesAllAsync("cupcakes", 37.786882, -122.399972);
            Console.WriteLine(results);
        }
    }
}

```

The good news is that I see the "remaining API calls" counter on my Yelp API account decrease every time I hit Debug. So I'm getting closer to getting the correct output!

**Comment by Pinski** [comment]
This is a standard thing in .NET.  

Your variable results is of type Yelp.Api.Models.SearchResponse.  Console.WriteLine expects a string.  SearchResponse has no .ToString function on it.  So when you take a type and cast it to a string, it just outputs the type name.

You'll need to actually output the data in some type of format that you wish.  For example:
```C#
Console.WriteLine(results.Total);
```

Or you could iterate over the `public IList<BusinessResponse> Businesses { get; set; }`

Again, my project has an entire working example project that demonstrates how to retrieve and display objects in this library.
https://github.com/Pinski/Yelp.Api.Web
