### ISSUE TITLE
Would you mind if I maintained a Web version of this?

### ISSUE THREAD

**Issue by Pinski** [madenwala/Yelp.Api#4]
Hello,

I've submitted a few pull requests to you of new functionality.  I'm using this in a web app and I think other people would want to use it for the web.  Would you mind if I maintained a fork of this and a NuGet that targets web apps?  I'd probably have it target various versions of netcoreapp.  

I would of course give you credit for starting it and link back to your original GitHub Repo and NuGet package.  I don't think I'd be adding any more functionality (for now) than what I've already submitted to you as a pull request.

Thanks.

**Comment by Pinski** [comment]
Hello,

Since I didn't hear back from you, I went ahead and uploaded a Web version of your NuGet package with the changes I made to your project via pull request.  

https://github.com/Pinski/Yelp.Api.Web
https://www.nuget.org/packages/Yelp.Api.Web/1.3.0

If for some reason this is a problem, please notify me.

Thanks for you help in getting this project started for me.

**Comment by madenwala** [comment]
Sorry for my late reply, @Pinski but I've merged your pull request.  It's up to you if you want to maintain your own request but I'll try to do a better job of checking this more often and accepting requests.
